document.writeln("<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional\/\/EN\" \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\">");
document.writeln("<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>");
document.writeln("<title>细览—右侧画中画js01<\/title>");
document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln("body { margin: 0px; padding: 0px;}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<table width=\"280\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><table width=\"280\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
document.writeln("        <tr> ");
document.writeln("          <td><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http:\/\/download.macromedia.com\/pub\/shockwave\/cabs\/flash\/swflash.cab#version=5,0,0,0\" width=\"280\" height=\"140\">");
document.writeln("              <param name=movie value=\"http:\/\/imgs.xinhuanet.com\/ad\/280140_shizheng.swf\">");
document.writeln("              <param name=quality value=high>");
document.writeln("              <param name=\"wmode\" value=\"transparent\">");
document.writeln("              <embed src=\"http:\/\/imgs.xinhuanet.com\/ad\/280140_shizheng.swf\" quality=high pluginspage=\"http:\/\/www.macromedia.com\/shockwave\/download\/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application\/x-shockwave-flash\" width=\"280\" height=\"140\">");
document.writeln("              <\/embed> ");
document.writeln("            <\/object><\/td>");
document.writeln("        <\/tr>");
document.writeln("      <\/table>");
document.writeln("      <table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
document.writeln("        <tr> ");
document.writeln("          <td height=\"8\"><\/td>");
document.writeln("        <\/tr>");
document.writeln("      <\/table>");
document.writeln("    <\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<\/body>");
document.writeln("<\/html>");