document.writeln("<table width=\"280\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><table width=\"280\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
document.writeln("        <tr> ");
document.writeln("          <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("            <tr>");
document.writeln("              <td><iframe src=\"http:\/\/imgs.xinhuanet.com\/ad\/20100930artxun200.html\" frameborder=\"0\" width=\"280\" scrolling=\"No\" height=\"200\"><\/iframe><\/td>");
document.writeln("            <\/tr>");
document.writeln("          <\/table>");
document.writeln("          <table width=\"86%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
document.writeln("            <tr>");
document.writeln("              <td height=\"8\"><\/td>");
document.writeln("            <\/tr>");
document.writeln("          <\/table>");
document.writeln("          <table width=\"280\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("            <tr>");
document.writeln("              <td><iframe src=\"http:\/\/www.xinhuanet.com\/classad\/xlwz_right_tf01.htm\" frameborder=\"0\" width=\"280\" scrolling=\"No\" height=\"80\"><\/iframe>                <\/td>");
document.writeln("            <\/tr>");
document.writeln("          <\/table><\/td>");
document.writeln("        <\/tr>");
document.writeln("      <\/table>");
document.writeln("      <table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">");
document.writeln("        <tr> ");
document.writeln("          <td height=\"8\"><\/td>");
document.writeln("        <\/tr>");
document.writeln("      <\/table>");
document.writeln("      ");
document.writeln("      <!-- 6条文字链的时候，iframe是105px的高度 --><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>")