---
title: "Overview"
output: html_document
---
## [第六次全国人口普查方案](http://www.stats.gov.cn/tjsj/pcsj/rkpc/6rp/html/fu07.htm)

### 二、人口普查的标准时点、对象和内容
- （六）人口普查的标准时点是**2010年11月1日**零时。
- （七）人口普查对象是指普查标准时点在中华人民共和国境内的自然人以及在中华人民共和国境外但未定居的中国公民，不包括在中华人民共和国境内短期停留的境外人员。
- （八）人口普查采用**按现住地登记**的原则。每个人必须在现住地进行登记。普查对象不在户口登记地居住的，户口登记地要登记相应信息。
- （九）人口普查以户为单位进行登记，户分为**家庭户**和**集体户**。以家庭成员关系为主、居住一处共同生活的人口，作为一个家庭户；**单身居住独自生活的，也作为一个家庭户**。相互之间没有家庭成员关系、集体居住共同生活的人口，作为集体户。
- （十）人口普查登记的主要内容包括：姓名、性别、年龄、民族、国籍、受教育程度、行业、职业、迁移流动、社会保障、婚姻、生育、死亡、住房情况等。
- （十一）人口普查表分为《第六次全国人口普查表短表》和《第六次全国人口普查表长表》。**普查表长表抽取10%的户填报；普查表短表由其余的户填报**。在境内居住的港澳台和外籍人员，在现住地进行登记，填写供港澳台和外籍人员使用的普查表短表。
- （十二）2009年11月1日至2010年10月31日期间有死亡人口的户，同时填报《第六次全国人口普查死亡人口调查表》。
- （十三）人口普查表由国务院第六次全国人口普查领导小组办公室（以下简称国务院人口普查办公室）和国家统计局统一制定，各省、自治区、直辖市人口普查办公室负责印发。
- （十四）中国人民解放军现役军人及军队管理的离退休人员，由军队领导机关统一进行普查、汇总。军队各类单位中服务的职工、文职人员、非现役公勤人员以及家属、保姆等，在军队营院内居住的，由军队机关负责普查，普查表移交当地人民政府指定的人口普查机构；不在军队营院内居住的，由地方人口普查机构负责普查。
- （十五）中国人民武装警察部队，由武警机关负责普查登记，普查表移交当地人民政府指定的人口普查机构。武警部队各类单位中服务的职工、非现役公勤人员以及家属、保姆等，在武警部队营院内居住的，由武警机关负责普查，普查表移交当地人民政府指定的人口普查机构；不在武警部队营院内居住的，由地方人口普查机构负责普查。
- （十六）驻外外交机构人员、驻港澳机构人员、其他各驻外机构人员以及派往境外的专家、职工、劳务人员、留学生、实习生、进修人员等，由其出国前居住的家庭户或者集体户申报登记。
- （十七）依法被判处徒刑、劳动教养的人员，由当地公安机关和监狱、劳教机关进行普查，普查表移交县、市人口普查办公室。